services:
  db:
    image: postgres:15
    container_name: shortener_db
    environment:
      POSTGRES_USER: url-shortener
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: urldb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shortener_app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: